COMPILER = g++
COMPILE_OPTION = -o

################################
# ALL COMPILE
################################
PROGRAM : BoardCover
all : $(PROGRAM)
clean: 
	@rm -f BoardCover *.o

$(PROGRAM)   : BoardCover.cpp
	$(COMPILER) $(COMPILE_OPTION) $(PROGRAM) $(PROGRAM).cpp

